Restructure filters
soerendolling/capstone-project-neue-fische pull request #25
Opened 2021-05-18 16:04 UTC by soerendolling

I have restructered the code on my filter pages and as well created a component for outdoor-page weather api

2021-05-18 19:59 UTC, FriederikeM approved these changes
Mate, i am jealous of your refactoring skills. Serious business 💪

2021-05-18 19:59 UTC, FriederikeM commented on src/components/AmbiencePage.js
> +          <FilterTagsRender filterPage="ambience" filterTags={tags} />
Woooouw, those are some serious refactoring skills

2021-05-18 19:59 UTC, FriederikeM commented on src/components/FilterTagsRender.js
> +  function isTagToogled(tagName) {
Toggled, rather than Toogled. Even though, I like the sound of toogled a lot more

2021-05-18 19:59 UTC, FriederikeM commented on src/components/OutdoorWeatherWidget.js
> +        console.log(error);
Maybe you can alert the error, or redirect to an error page. The user probably won't check the console

2021-05-19 07:53 UTC, OwnTooManyMonster reviewed
Nice and clean!

2021-05-19 08:48 UTC, namirsab requested changes
Hey @soerendolling 
amazing refactoring, really well done. You've removed a lot of code!
Please take a look to my comments

2021-05-19 08:48 UTC, namirsab commented on src/components/FilterTagsRender.js
> +import { toggleValueInArray } from "../utilities/filters/toggleValueInArray";
The `toggleValueInArray` utility could be saved just under `utilities` as it's not really a filter

2021-05-19 08:48 UTC, namirsab commented on src/components/OutdoorWeatherWidget.js
> +  const [weather, setWeather] = useState();
you could have state to handle if the widget is loading and if the widget has errored, and then render it accordingly.

https://codesandbox.io/s/usefetch-6boe7?file=/src/App.js

in that codesandbox you can see what I mean

2021-05-19 08:48 UTC, namirsab commented on src/components/FilterTagsRender.js
> +export default function FilterTagsRender({ filterPage, filterTags }) {
I wouldn't append `Render` to the name of the component. I'm sure you can find a better name

2021-05-19 09:31 UTC, merged